services:
  explorer:
    container_name: fhir_db
    image: kuzudb/explorer:0.11.0
    environment:
      - MODE=READ_ONLY
      - KUZU_FILE=fhir_db.kuzu
    ports:
      - 8000:8000
    volumes:
      - ./:/database
